### ISSUE TITLE
`AttributeError: 'csc_matrix' object has no attribute 'A1'` in MultiLCA

### ISSUE THREAD

**Issue by mgo-cea** [brightway-lca/brightway2-data#244]
I've come up with a weird behavior of `multiLCA` throwing an `AttributeError: 'csc_matrix' object has no attribute 'A1'` exception error. I've seen brightway-lca/brightway2-calc#123 and was about to apply the proposed recipe. However, I also discovered that if I compute first the individual LCAs, then compute with `multiLCA`, the exception is not thrown!

See attached for an example. I'm using here the helper methods of `lca_algebraic` to ease the creation, but be sure that I'm working with BW2.5.
[err_multiLCA.txt](https://github.com/user-attachments/files/20820829/err_multiLCA.txt)

**Comment by mgo-cea** [comment]
For your information, a call to `bw2data.databases.clean()` before launching the first `MultiLCA` solves the issue.
A similar call is made inside `prepare_lca_inputs` , but not within `get_multilca_data_objs`. I don't know if it's worth (or even sensible) adding it to make it more robust.

**Comment by cmutel** [comment]
Seems like this is a simple fix - `get_multilca_data_objs` needs to call `bw2data.databases.clean()`. Needs a PR with a test case to fix.

Thanks @mgo-cea

**Comment by mgo-cea** [comment]
Hi Chris,
I'm trying to close this by submitting the a PR as requested. I'm struggling though to create a minimal test case demonstrating the issue, as I'm not exactly sure which are the data that need to be "cleaned".
